export const SESSION_VIEW = 'SESSION_VIEW'
export const SESSION_START = 'SESSION_START'
export const SESSION_START_COMPLETE = 'SESSION_START_COMPLETE'
export const SESSION_DELETE = 'SESSION_DELETE'
export const SESSION_DELETE_COMPLETE = 'SESSION_DELETE_COMPLETE'
export const SESSION_UPDATE = 'SESSION_UPDATE'
export const SESSION_SUBMIT_TIME = 'SESSION_SUBMIT_TIME'
export const SESSION_SUBMIT_TIME_COMPLETE = 'SESSION_SUBMIT_TIME_COMPLETE'

export const USERS_IMPORT = 'USERS_IMPORT'
export const USERS_IMPORT_SUCCESS = 'USERS_IMPORT_SUCCESS'
export const USERS_REGISTER = 'USERS_REGISTER'
export const USERS_REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS'

export const NEW_CARD_RECIEVED = 'NEW_CARD_RECIEVED'

export const RECIEVE_SESSIONS = 'RECIEVE_SESSIONS'
export const RECIEVE_UPDATE = 'RECIEVE_UPDATE'
export const CHANGE_SETTINGS = 'CHANGE_SETTINGS'
export const CHANGE_SETTINGS_COMPLETE = 'CHANGE_SETTINGS_COMPLETE'

export const SERVER_ERROR_LOG = 'SERVER_ERROR_LOG'
export const SERVER_CONNECTED = 'SERVER_CONNECTED'
export const SERVER_DISCONNECTED = 'SERVER_DISCONNECTED'
export const SERVER_CONNECTION_FAILED = 'SERVER_CONNECTION_FAILED'

export const NOTIFICATION_ADDED = 'NOTIFICATION_ADDED';
export const NOTIFICATION_REMOVED = 'NOTIFICATION_REMOVED';
export const NOTIFICATION_CLEAR = 'NOTIFICATION_CLEAR';


    //
    // USER_IMPORT: null,
    // USER_UPDATE: null,
    // USER_ASSIGN_CARD: null,
    // USER_REMOVE_CARD: null,
