export const SESSION_DELETE = 'SESSION_DELETE'
﻿export const SESSION_UPDATE = 'SESSION_UPDATE'
export const SESSION_SUBMIT_TIME = 'SESSION_SUBMIT_TIME'
export const USERS_IMPORT = 'USERS_IMPORT'
export const RECIEVE_SESSIONS = 'RECIEVE_SESSIONS'
export const RECIEVE_UPDATE = 'RECIEVE_UPDATE'
export const CHANGE_SETTINGS = 'CHANGE_SETTINGS'
export const CHANGE_SETTINGS_COMPLETE = 'CHANGE_SETTINGS_COMPLETE'

export const SERVER_ERROR_LOG = 'SERVER_ERROR_LOG'
export const SERVER_CONNECTED = 'SERVER_CONNECTED'
export const SERVER_DISCONNECTED = 'SERVER_DISCONNECTED'
export const SERVER_CONNECTION_FAILED = 'SERVER_CONNECTION_FAILED'


    //
    // USER_IMPORT: null,
    // USER_UPDATE: null,
    // USER_ASSIGN_CARD: null,
    // USER_REMOVE_CARD: null,
